services:
  watchtower:
    image: ghcr.io/containrrr/watchtower:1.7.1
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      # This will remove old not used images
      WATCHTOWER_CLEANUP: "true"
      TZ: "UTC"
      # 0-6 or SUN-SAT: So I want Mo-Fr at 6
      WATCHTOWER_SCHEDULE: "0 0 6 * * 1-5"
      # WATCHTOWER_POLL_INTERVAL: 60
      WATCHTOWER_TIMEOUT: "30s"
      # Mail setup
      WATCHTOWER_NOTIFICATIONS: "email"
      WATCHTOWER_NOTIFICATION_EMAIL_FROM: "${WATCHTOWER_EMAIL_FROM}"
      WATCHTOWER_NOTIFICATION_EMAIL_TO: "${WATCHTOWER_EMAIL_TO}"
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER: "smtp.gmail.com"
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT: 587
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER: "${WATCHTOWER_EMAIL_USER}"
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD: "${WATCHTOWER_SMTP_PASSWORD}"
      WATCHTOWER_NOTIFICATION_EMAIL_DELAY: 10
      WATCHTOWER_DEBUG: "false"
    restart: unless-stopped

networks:
  proxy-network:
    external: true
    name: proxy-network